import React, { useEffect } from "react";
import ButtonWithSound from "./ButtonWithSound.tsx";
import backgroundMusicFile from "../assets/game-music.mp3";

interface FinalScreenProps {
  score: number;
  onPlayAgain: () => void;
}

const FinalScreen: React.FC<FinalScreenProps> = ({ score, onPlayAgain }) => {

  useEffect(() => {
    const backgroundMusic = new Audio(backgroundMusicFile);
    backgroundMusic.volume = 0.3;
    backgroundMusic.loop = true; 
    backgroundMusic.play().catch((err) => console.error("Audio Error:", err));
    return () => {
      backgroundMusic.pause(); 
      backgroundMusic.currentTime = 0;
    };
  }, []);

  return (
    <div className="h-screen bg-black text-white flex flex-col items-center justify-center">
      <h1 className="text-5xl font-bold mb-4 text-green-200 animate-pulse">Mission Accomplished!</h1>
      <p className="text-2xl mb-4">Congratulations, Agent!</p>
      <p className="text-xl mb-6">Final Score: {score}</p>
      <ButtonWithSound
        className="bg-green-600 text-black px-6 py-2 rounded-lg hover:text-white hover:bg-gray-800 border-4 border-gray-800"
        onClick={onPlayAgain}
      >
        Play Again
      </ButtonWithSound>
      <div className="mt-12 text-gray-400">
        <p className="text-xl text-center my-2 underline">Game Credits</p>
        <p>Developed by <b>Abdul Wajid Parray</b></p>
        <p>Images: Generated by Gemini</p>
        <p>Graphics and Icons: Canva, Pixabay</p>
        <p>Music and Sounds: Free Resources</p>
      </div>
    </div>
  );
};

export default FinalScreen;
